### ISSUE TITLE
New waiting list

### ISSUE THREAD

**Issue by mubes** [orbcode/orbtrace#11]
This is a new waiting list for ORBTrace hardware for use while zyp is on vacation and the store is closed. Please add your name to this list and everyone on it will get 24 hours notice to place an order before the store is publicly re-opened.  This isn't a hard commitment to buy anything; It just makes sure you're at the head of a queue.

**Comment by shareefj** [comment]
Me me me.

**Comment by cstrahan** [comment]
I, @cstrahan, would like a heads up :)

**Comment by sierrajanderson** [comment]
I'd love a heads up please :)

**Comment by gojimmypi** [comment]
Yes, please.

**Comment by tymmothy** [comment]
Me too please

**Comment by hetul317** [comment]
I’d like to know when the store reopens please! Thank you

**Comment by IGate68** [comment]
Yes please

**Comment by mgjmm** [comment]
Please include me on the waiting list

**Comment by ProfessorGearchange** [comment]
Yes please.

**Comment by mubes** [comment]
Folks, zyp has just opened the store up if you want to place an order. It's at https://store.zyp.no/  There is absolutely no commitment to do so ... feel free to ignore this note.  The few that are left will be allocated on a first-come-first-served basis and when they're gone it'll be a while before there are any more. Please restrict yourselves to a maximum of one (but I _highly_ recommend getting some extra connecting cables!).  Orders will ship on Monday, assuming you get them in in time.

Thanks for being patient. This issue will now be closed and anyone joining the next issue will have quite a bit longer wait I'm afraid.

**Comment by gojimmypi** [comment]
Greetings ORBTrace enthusiasts! In particular new owners: I have a [blog](https://gojimmypi.github.io/orbtrace-mini-initial-setup/) that documents my journey on getting my board upgraded. 

It was quite a learning opportunity that I probably could not have completed without the help of @mubes  @zyp  and others on the Discord channel. Hopefully my notes will help others.

There's also a TL;DR in https://github.com/orbcode/orbtrace/issues/12#issuecomment-1365493172
