### ISSUE TITLE
Which is the correct device ID?

### ISSUE THREAD

**Issue by gojimmypi** [orbcode/orbtrace#12]
The [build instructions](https://github.com/orbcode/orbtrace#building) indicate that the orbtrace USB ID should be specified as `1209:3442`:

```
dfu-util -d 1209:3442 -a 1 -D build/orbtrace_mini/gateware/orbtrace_mini.bit
                    |
```

But I see `1209:3443` (a three in the last digit) in Zadig:

![image](https://user-images.githubusercontent.com/13059545/209570268-eb006062-cfcd-4671-8782-e2f513bd8d96.png)

Are there different versions of the board to be aware of, or is that simply a typo in the README?

**Comment by mubes** [comment]
3442 is the device in upgrade mode (i.e. that will receive dfu requests).
You put it into dfu mode by holding down the button while powering it up.
In 'normal operation' the full device id is 1209:3443.

Regards

Dave

**Comment by gojimmypi** [comment]
Ah yes, I was confused a bit about the device ID values. Let me copy some text from [my blog](https://gojimmypi.github.io/orbtrace-mini-initial-setup/) here for reference to future newbies:

I realized I was confusing the bootloader (aka gateware) with the application. I ended up completing my upgrade steps in an Ubuntu VM, not Windows.

`Bootloader mode` is when the purple light is on. Key here: HOLD DOWN the button while powering the device up UNTIL the light turns purple.

When in bootloader mode, the USB Device ID is `1209:3442`. That last digit is a TWO!

When NOT in bootloader mode, he USB Device ID is `1209:3443`. That last digit is a THREE!

Be sure to specify a slot for `dfu-util` (the `-a` parameter); Slot 0 is not used.

The application gets loaded into SLOT 1 with the `dfu-util` parameter `-a 1`.

The bootloader gets loaded into SLOT 2 with the `dfu-util` parameter `-a 2`.

BE SURE to not mix up the slot numbers with application vs bootloader. If you do, well, don't power cycle until you load the correct one in the proper slot.

When in bootloader mode, power cycle to return to operational mode. The device ID will change from `1209:3442` to `1209:3443`.

Note there are [build instructions](https://github.com/orbcode/orbtrace#building) and slightly different instructions on the [release page](https://github.com/orbcode/orbtrace/releases). The release instructions are a bit more clear at the time of this blog.

BOTH the application AND bootloader need to have the purple light on to load.

```
# application in slot 1
dfu-util -d 1209:3442 -a 1 -D orbtrace_mini_application_1.2.0.bit

# bootloader (aka gateware) in slot 2
dfu-util -d 1209:3442 -a 2 -D orbtrace_mini_bootloader_1.2.0.bit
```
