### ISSUE TITLE
Error: CMSIS-DAP command CMD_DAP_SWJ_CLOCK failed

### ISSUE THREAD

**Issue by augustofg** [orbcode/orbtrace#22]
When trying to connect with a target using openocd I get the error `CMSIS-DAP command CMD_DAP_SWJ_CLOCK failed`:
```
$ openocd  -f interface/cmsis-dap.cfg -c "transport select jtag" -c "adapter speed 1000" -f target/lpc17xx.cfg 
Open On-Chip Debugger 0.12.0+dev-00292-g1a6194b73 (2023-12-12-10:41)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
jtag
adapter speed: 1000 kHz
cortex_m reset_config sysresetreq
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Using CMSIS-DAPv2 interface with VID:PID=0x1209:0x3443, serial=3398708163008E06
Info : CMSIS-DAP: SWD supported
Info : CMSIS-DAP: JTAG supported
Info : CMSIS-DAP: FW Version = 2.1.0
Info : CMSIS-DAP: Interface Initialised (JTAG)
Info : SWCLK/TCK = 1 SWDIO/TMS = 0 TDI = 1 TDO = 0 nTRST = 1 nRESET = 0
Error: CMSIS-DAP command CMD_DAP_SWJ_CLOCK failed.
```
I've flashed `orbtrace` with the last release (v1.3.2), but still experiencing the same error. Tried with different versions of openocd. Any guess what I'm doing wrong?

**Comment by mubes** [comment]
Hi. For whatever reason, you're asking for a clock that is outside of the allowed range. From what you've posted above it looks like you're asking for 1MHz which should be fine. Range is ~200KHz to 25MHz. You might try just removing the `-c` or putting it at the end of the line. Let us know if it helps.

**Comment by mubes** [comment]
Thats odd because I looked quickly at the `target/lpc17xx.cfg` script on my own machine and didn't see any clock setting steps there. Oh well, at least you found it. I'll close this off now.
