### ISSUE TITLE
What is the trace clock and targets supported for Orbtrace Mini

### ISSUE THREAD

**Issue by retif** [orbcode/orbtrace#25]
Hello, i have ordered the orbtrace mini, a decent device, thank you!
Other tracing probes state **Trace Clock** characteristic, like 120MHz for QTrace.

1. What is Trace Clock for orbtrace mini?
2. What is the max MCU speed in MHz?
3. is ETMv3.5 for instruction and data trace?
4. Please, suggest a way to filter for supported stm32 chips (caps to ETMv3.5)
5. How far is ETMv3.5 is backward-compatible?
6. Is there milestones for next ETM versions?

Thanks!

**Comment by zyp** [comment]
1. We're currently building with a constraint on the trace clock set to 120MHz, ref. [here](https://github.com/orbcode/orbtrace/blob/main/orbtrace/platforms/orbtrace_mini.py#L204). The constraint is met in the build, but we haven't yet done a lot of benchmarking in practice. I expect that once we find time to do some work on benchmarking and optimizations, we might be able to raise the constraint to a higher number.
2. Do you mean the target MCU? There's no direct limits on that, but if the MCU has a fixed divider between the CPU clock and the trace clock, the CPU clock would be limited to whatever keeps the trace clock within 120MHz.
3. I believe so, although my impression is that MCUs often only implement instruction trace, not data trace.
4. I believe Cortex-M4 and older will have ETMv3, while Cortex-M7 and newer will have ETMv4. Note that Orbuculum does have some ETMv4 support now, although I'm not sure how mature it is yet.
5. I don't know. I believe anything Cortex-M is at least v3 and I'm not familiar with anything older.
6. Like I mentioned above, Orbuculum does already have some ETMv4 support.

Note that this repository (Orbtrace) is for the trace capture device so while questions about stuff like capture speed belong here, questions that regards the analysis software like support for different ETM versions are better posed in the [Orbuculum](https://github.com/orbcode/orbuculum) repository.
