### ISSUE TITLE
trying orbtrace on a custom fpga board

### ISSUE THREAD

**Issue by abisop** [orbcode/orbtrace#27]
can someone explains what orbtrace directory is for

**Comment by mubes** [comment]
Sorry, there is not enough information here to be able to give a useful response. Can you please expand your question - what are you trying to do, and where are you getting stuck?

**Comment by abisop** [comment]
Thanks for responding
Actually here in India orbtrace hardware or lattice fpga is not available available.
I am trying to use rtl code for altera cyclone fpga and usb2 hs module.

can you please suggest me how to proceed right way.

**Comment by mubes** [comment]
Hi, Im afraid that is a chunk of work that you will need to attack for
yourself...its quite significant. It should be possible to get the code
working for such a configuration but it depends on a lot of details that
are beyond a support question.  ORBTrace should be available in India, so
far as I am aware zyp is capable of shipping pretty much anywhere that
isn't under embargo...drop him a note or ask a question in the discord if
you have problems.
