### ISSUE TITLE
Implement DAP_SWD_Sequence

### ISSUE THREAD

**Issue by UweBonnes** [orbcode/orbtrace#4]
According to https://arm-software.github.io/CMSIS_5/DAP/html/dap_revisionHistory.html, since V1.2  DAP_SWD_Sequence is part of the specification. orbtrace needs to be V2 to allow "Communication via WinUSB to achieve high-speed transfer rates". So if applications see   version >= 1.2 they will use DAP_SWD_Sequence where needed, e.g. for Multidrop. Even if the application provides a fallback for needed DAP_SWD_Sequence , emulation with DAP_SWJ_Pins  is impossible, as SWDIO can not be made to float.

**Comment by mubes** [comment]
I believe this is now resolved in 4d7bac6. Please yell up if you see issues and have a test case that demonstrates any problems and we'll get them fixed.

**Comment by UweBonnes** [comment]
If you can, test by scanning a PR2040 with a blackmagic  probe.

**Comment by mubes** [comment]
Yes, that works fine;

`(gdb) target extended-remote localhost:2000
Remote debugging using localhost:2000
(gdb) monitor swd
Available Targets:
No. Att Driver
 1      Raspberry RP2040 M0+
 2      Raspberry RP2040 M0+
 3      Raspberry RP2040 Rescue(Attach to reset!) 
(gdb) att 1
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x100050d6 in ?? ()
(gdb) 
`
